<?php
/**
 * Created by PhpStorm.
 * User: dylan
 * Date: 12/12/2017
 * Time: 13:59
 */

namespace AppBundle\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface;
use Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler;
use Symfony\Component\Security\Http\HttpUtils;

class AuthenticationSuccessHandler extends DefaultAuthenticationSuccessHandler
{

 /**
    private $flashBag;

    public function __construct(HttpUtils $httpUtils, array $options = array(), FlashBagInterface $flashBag)
    {
        parent::__construct($httpUtils, $options);

        $this->flashBag = $flashBag;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token)
    {
        $this->session->getFlashBag()->add('success', 'Success');

        return parent::onAuthenticationSuccess($request, $token); // TODO: Change the autogenerated stub
    }*/
}