<?php
/**
 * Created by PhpStorm.
 * User: dylan
 * Date: 12/12/2017
 * Time: 14:00
 */

namespace AppBundle\Security;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\HttpKernel\HttpKernelInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface;
use Symfony\Component\Security\Http\Authentication\DefaultAuthenticationFailureHandler;
use Symfony\Component\Security\Http\HttpUtils;

class AuthenticationFailedHandler extends DefaultAuthenticationFailureHandler
{


    /**
    private $flashBag;

    public function __construct(HttpKernelInterface $httpKernel, HttpUtils $httpUtils, array $options = array(),
                                LoggerInterface $logger = null, FlashBagInterface $flashBag)
    {
        parent::__construct($httpKernel, $httpUtils, $options, $logger);
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $this->flashBag->add('warning', 'Denied');
        return parent::onAuthenticationFailure($request, $exception); // TODO: Change the autogenerated stub
    }
     * */
}